name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libtinfo6

      - name: Install Python tools
        run: |
          pip install --upgrade pip wheel
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug \
            -- \
            --ndk_version=23b \
            --sdk_version=34

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lasercalc.apk
          path: bin/*.apk
          if-no-files-found: error
