name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libtinfo6 \
            libffi-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython virtualenv

      - name: Prepare environment
        run: |
          mkdir -p .buildozer/android/platform
          buildozer android clean
          buildozer android update

      - name: Build APK
        run: |
          buildozer -v android debug \
            -- --ndk_version=23b --sdk_version=34
          ls -la bin/

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: lasercalc.apk
          path: bin/*.apk
          retention-days: 1
